### ISSUE TITLE
Mail2000 的網頁裡頭的 mail 檢視無法加空格

### ISSUE THREAD

**Issue by sujunmin** [vinta/pangu.js#100]
[Openfind Mail2000](https://www.mail2000.com.tw/) 的信件檢視裡無法自動加空格，附上 Dom 的截圖，感覺是個 frame 裡頭又有個 iframe。

![2017-05-31 13 14 30](https://cloud.githubusercontent.com/assets/6415168/26616768/ae5ea5a2-4603-11e7-8e01-75422759eb61.png)

**Comment by vinta** [comment]
如果是在 `<iframe>` 裡面的內容的話，因為瀏覽器的限制，應該是無能為力了啦
