### ISSUE TITLE
写了一个 pangu 的 VS Code extension

### ISSUE THREAD

**Issue by baurine** [vinta/pangu.js#103]
Hi @vinta ，

我最近为 pangu 写了 VS Code extension，以下分别是 GitHub 和 Marketplace 的链接：

- [GitHub Repo](https://github.com/baurine/vscode-pangu)
- [Marketplace](https://marketplace.visualstudio.com/items?itemName=baurine.vscode-pangu)

可否加到您的 README 中？

谢谢！

**Comment by vinta** [comment]
@baurine 可以啊，你可以直接發個 pull request，放在 Related Projects 底下，按照字母順序排即可

**Comment by baurine** [comment]
@vinta 已提交 PR #104 ，谢谢！
