### ISSUE TITLE
会导致哔哩哔哩有些视频无法显示

### ISSUE THREAD

**Issue by Augusmmm** [vinta/pangu.js#109]
https://www.bilibili.com/     某些视频无法显示

**Comment by kongwy** [comment]
同样遇到这个问题，Chrome 扩展导致 Bilibili 部分视频页面（例如[这个](https://www.bilibili.com/video/av96911/)）的新版 HTML5 播放器在加载过程中消失，导致视频无法播放。

在扩展选项中添加例外 `//bilibili.com` 亦无效。

**Comment by laxect** [comment]
再提供一个样本 https://www.bilibili.com/video/av7856822?from=search&seid=6394154271771601643

**Comment by duanluan** [comment]
确实……我还以为是什么脚本的问题呢，后来发现是这儿的问题，视频直接消失了。

**Comment by YeungKC** [comment]
(´･_･`) 望尽快更新…很影响日常使用
