### ISSUE TITLE
如何删除省略号后面的空格？

### ISSUE THREAD

**Issue by shioko** [vinta/pangu.js#114]
自己在JS里捣鼓半天了，没成功\_(:з」∠)\_
使用的是theme-next-pangu，但是那边的issues好像没人看的样子

**Comment by shioko** [comment]
呃我自己解决了，在js里搜索`\u2026`，js.map里搜索'\\u2026`全部替换掉就不会加空格了_(:з」∠)_

**Comment by shioko** [comment]
对不起我又来了；▽；
空格只在本地成功被去掉了，我部署上传之后又出现了空格，这是为什么啊_(:з」∠)_……
如图
![](https://cmx.im/system/media_attachments/files/001/188/662/original/e36e249c42adba30.png?1542956187)
![](https://cmx.im/system/media_attachments/files/001/188/664/original/998c79c0f543b6cf.png?1542956230)

**Comment by vinta** [comment]
Won't fix.
