### ISSUE TITLE
不加空格的半角标点

### ISSUE THREAD

**Issue by rikakomoe** [vinta/pangu.js#115]
[间隔号](https://baike.baidu.com/item/%E9%97%B4%E9%9A%94%E5%8F%B7) `·` （`\u00b7`）是一个中文非常常用的**半角**符号：

+ 海伦·凯勒，马克·吐温
+ 《论语·里仁》，《孟子·梁惠王》
+ “一二·九”运动，“九·一八”事变

**Comment by rikakomoe** [comment]
此外还有半角符号 `/`，例如：公里/小时

**Comment by FranklinYu** [comment]
亦可同時參照維基百科的[間隔號](https://zh.wikipedia.org/wiki/间隔号)和[斜線](https://zh.wikipedia.org/wiki/斜線)。

**Comment by rikakomoe** [comment]
#88 的 `\u30fb` 是一个全角符号，全角符号两侧本身就是不应该加空格的，所以 #88 那个问题是全角符号被当成汉字问题。
`\u00b7` 是一个半角符号，这个 issue 是关于中文中会用到的半角符号的问题 :+1:

**Comment by FranklinYu** [comment]
爲何關閉？
