### ISSUE TITLE
培養用戶習慣，對插件的變動進行醒目提示？

### ISSUE THREAD

**Issue by Sharuru** [vinta/pangu.js#66]
首先要說的是這個插件真的是太有用辣！感謝作者以及相關貢獻人員的努力。 :smile: 

在瀏覽網頁或者審查自己網站的過程中，有時候我很想知道頁面中的哪些空格是由插件完成的，這個時候我只能不斷的刷新頁面來進行比對；於是我想到了一個功能，可以設置對那些由插件插入的空格進行提示（比如呈現黃色高亮狀態，2、3秒后隱去），起到提醒的同時又不過於影響頁面瀏覽。

不知道我這個想法如何？ :eyes: 

P.S. “不要再他妈「空格之神显灵了」！”這個選項真的是太搞笑了！

**Comment by vinta** [comment]
Won't fix.
