### ISSUE TITLE
不要對 GitHub 上的程式碼頁面加空格

### ISSUE THREAD

**Issue by vinta** [vinta/pangu.js#70]
例如 https://github.com/vinta/pangu/blob/master/pangu_test.go

可能可以把 url pattern 加入黑名單？

**Comment by vinta** [comment]
目前只好在黑名單裡加入 `/blob/master/` 擋一下先

**Comment by acgtyrant** [comment]
没用诶，每次编辑 README 就自动启动，好多字都错位了。

**Comment by vinta** [comment]
@acgtyrant 那個頁面的 URL 是？

**Comment by acgtyrant** [comment]
https://github.com/acgtyrant/ACUR/edit/master/mechanism.md

此外光屏蔽 `/blob/master/` 也不够诶，万一人家访问的是其它分支呢？

**Comment by acgtyrant** [comment]
`github.com/[\w]*/[\w]*/[edit|blob]/*/` 之类的就行了。

**Comment by vinta** [comment]
應該用 https://github.com/vinta/pangu.js/issues/124 解決，先關
