### ISSUE TITLE
Sometimes not working while using Google Hangouts

### ISSUE THREAD

**Issue by Cee** [vinta/pangu.js#78]
![test image](https://cloud.githubusercontent.com/assets/5436953/10313896/83bcbe88-6c84-11e5-993c-7198f572dec5.gif)

**Comment by vinta** [comment]
好！我會找個時間查一下這個問題。

**Comment by Cee** [comment]
@vinta 煩請您看一下 Safari 的支持！（#77）

**Comment by vinta** [comment]
沒問題，晚上我測試看看
