### ISSUE TITLE
Universal JavaScript

### ISSUE THREAD

**Issue by vinta** [vinta/pangu.js#80]
make pangu compatible with server and browser

**Comment by huei90** [comment]
@vinta Do you mean support both node and browser?
If yes, `pangu.node` may concern depreciation.

**Comment by vinta** [comment]
@huei90 Yes, I'm working on making this library support both environments. It may take some time.

**Comment by huei90** [comment]
Ok, thank you for your prompt reply. :beers:

**Comment by vinta** [comment]
Done!

https://github.com/vinta/pangu.js/tree/master/src

**Comment by huei90** [comment]
pangu.node is now refer to pangu.js

https://github.com/huei90/pangu.node

**Comment by vinta** [comment]
@huei90 :+1:
