### ISSUE TITLE
直接處理 HTML 的話會得到不正確的結果

### ISSUE THREAD

**Issue by alemonmk** [vinta/pangu.js#81]
這個問題主要是在用 hexo-filter-auto-spacing (內部呼叫了 pangu.node 的 `insert_space()`) 發現的。
雖然 pangu.node 的代碼應該頗為老舊，但是我試著置換它的 browser demo 用的代碼發現問題依舊。

來個例子～
輸入:

``` html
字字字<abbr title="">縮寫</abbr>，字字字
```

輸出:

``` html
字字字 <abbr title=""> 縮寫</abbr>，字字字
```

輸入:

``` html
字字字<abbr title="">縮寫</abbr>，<abbr title="">縮寫</abbr>，<abbr title="">縮寫</abbr>字字字
```

輸出:

``` html
字字字 <abbr title=""> 縮寫 </abbr>，<abbr title=""> 縮寫 </abbr>，<abbr title=""> 縮寫 </abbr> 字字字
```

預期結果是沒有改動。更怪的是這兩組結果並不一致。這有解嗎？

**Comment by vinta** [comment]
那個判斷 HTML tag 插空格的邏輯太複雜了
畢竟 tag 嵌套起來真的不是開玩笑的
請給我一點時間研究一下

**Comment by alemonmk** [comment]
想了一下這個 issue 應該發在下游的（甚至是那個 hexo filter ），抱歉打擾了...
但不管 hexo-filter-auto-spacing 還是 pangu.node 最後都是會遇到一個問題 - 這個函式是要處理 md 還是 HTML orz

**Comment by huei90** [comment]
> pangu.node 的代碼應該頗為老舊
是的，真的很老舊了。要花多一點時間回去看

**Comment by vinta** [comment]
處理 .md 和處理 .html 應該是要分成兩個 methods
畢竟實作的方式會完全不同
