### ISSUE TITLE
造成 Google 圖片搜尋 異常

### ISSUE THREAD

**Issue by flirmnave** [vinta/pangu.js#84]
使用環境：
-    Chrome 48.0.2564.109  
      為什麼你們就是不能加個空格呢？ 2.5.7(附加元件)  
-    Firefox 42.0  
      Greasemonkey 3.6  
      為什麼你們就是不能加個空格呢？ 2.5.6(腳本)  

> ## 將 為什麼你們就是不能加個空格呢 關閉
> 
> 正常情況下點擊Google圖片的搜尋結果
> 會跳出下方黑色區塊預覽窗格
> [正常](http://i.imgur.com/uKWoaPL.jpg)  
> ## 將 為什麼你們就是不能加個空格呢 開啟
> 
> 異常情況下點擊Google圖片的搜尋結果
> 無法跳出下方黑色區塊預覽窗格
> [異常](http://i.imgur.com/0tJu1DZ.jpg)  

測試 Firefox Chrome 皆是相同的情況

**Comment by vinta** [comment]
原來是這個外掛啊

臨時的解法是把 google image 加入黑名單
在外掛的 option page 可以設定

**Comment by flirmnave** [comment]
目前重新測試了一次

- Firefox 42.0  
Greasemonkey 3.6  
為什麼你們就是不能加個空格呢？ 2.5.6(腳本)  
- Chrome 48.0.2564.116 m  
Tampermonkey 3.12.58
為什麼你們就是不能加個空格呢？ 2.5.6(腳本)  

以上兩種情況Google圖片搜尋出來是正常可使用的  
* * *
而以下
- Chrome 48.0.2564.116 m  
為什麼你們就是不能加個空格呢？ 2.5.7(附加元件)

這個情況還是有問題
* * *
所以在Chrome我暫時改回使用腳本的方式了

**Comment by vinta** [comment]
補充一下，暫時的解法是在 Options 頁的黑名單裡加上 `&tbm=isch`

<img width="573" alt="screen shot 2016-06-25 at 20 22 36" src="https://cloud.githubusercontent.com/assets/652070/16356649/9dcf7ace-3b12-11e6-8b54-947b296745a1.png">

**Comment by royhsu** [comment]
在 Safari 版本 10.0.2（12602.3.12.0.1）有一樣的問題

**Comment by kongwy** [comment]
被困扰了快两年今天才发现了问题在这里……

**Comment by romeo0930** [comment]
2018年3月，還是沒更新，可惜....
插件版本：2.5.6
火狐：57.0.4
