### ISSUE TITLE
下载 cmct.tv 论坛附件文件自动在后缀添加空格

### ISSUE THREAD

**Issue by sarkrui** [vinta/pangu.js#89]
<img width="873" alt="2016-08-24 1 31 29" src="https://cloud.githubusercontent.com/assets/14228455/17919302/1c6607ca-69ff-11e6-9cdf-6988d97cbf64.png">
<img width="515" alt="2016-08-24 1 30 28" src="https://cloud.githubusercontent.com/assets/14228455/17919303/1cae09d0-69ff-11e6-9fb0-4a4b0a9c8d41.png">
目前我暂时性解决方法是把cmct.tv添加进黑名单
<img width="411" alt="2016-08-24 1 32 41" src="https://cloud.githubusercontent.com/assets/14228455/17919329/4ec1c100-69ff-11e6-9a22-dfe5f2cb735e.png">

**Comment by vinta** [comment]
雖然跟 issue 本身無關
但是你用了這個外掛卻在開 issue 的時候仍舊沒有空格
這樣真的不行

**Comment by vinta** [comment]
會在 https://github.com/vinta/pangu.js/issues/107 裡解決，先關閉
