### ISSUE TITLE
希望更新 Userscript 脚本

### ISSUE THREAD

**Issue by h2y** [vinta/pangu.js#90]
https://greasyfork.org/zh-CN/scripts/2185

这里下载的版本相比 Git 落后了好多，希望更新一下，挺好用的。

另外对于 #84 问题可以排除这个链接来暂时解决：

`/^https://www.google\..+tbm=isch/`

**Comment by vinta** [comment]
似乎是需要自動化一下
不然老是會忘記

**Comment by millionart** [comment]
希望作者下次看到这里能抽空更新下，现在已经导致新版的bilibili部分视频无法显示了
比如
https://www.bilibili.com/video/av28216935
https://www.bilibili.com/video/av29799209

**Comment by millionart** [comment]
但以上两个视频（新版哔哩哔哩）还是会被此脚本隐藏

**Comment by ShenHongFei** [comment]
https://github.com/vinta/pangu.js/issues/101#issuecomment-450858716
解决了 bilibili 问题和性能问题。
