### ISSUE TITLE
处理 markdown 内容时的问题

### ISSUE THREAD

**Issue by akuma** [vinta/pangu.js#91]
在用 pangu.js 处理 markdown 内容时格式上会有一些不希望的结果，例如：

```md
*你好*world。
```

会处理成：

```md
* 你好 * world。
```

最好是：

```
*你好* world。
```

PS. 我整合一个命令行的版本：[pangu-cli](https://github.com/akuma/pangu-cli) :)

**Comment by VincentBel** [comment]
我写了一个 remark 插件（[remark-pangu](https://github.com/VincentBel/remark-pangu)）处理 Markdown:

![image](https://user-images.githubusercontent.com/6076919/30221639-a1aee28a-94f6-11e7-91ed-d27c6782fd40.png)

```bash
$ npm install -g remark-cli remark-pangu 
$ remark -u remark-pangu ./test.md
```

**Comment by vinta** [comment]
`pangu.spacing()` 是針對純文字設計的，如果要處理特定格式的檔案，實際上要複雜得多。例如 HTML，詳見 https://github.com/vinta/pangu.js/blob/master/src/browser/pangu.js

目前 `pangu.spacing()` 不打算針對 Markdown 做特別支援。
