### ISSUE TITLE
数字与单位之间还是需要空格嘛？

### ISSUE THREAD

**Issue by jeopsh** [vinta/pangu.js#93]
参考这个指南，加上空格效果更好呢。
[中文文案排版指北](https://github.com/mzlogin/chinese-copywriting-guidelines/blob/Simplified/README.md)

还有学术论文也要求加空格耶。
[論文寫作注意事項](http://homepage.ntu.edu.tw/~jmhu/hulab/Thesis_guideline.pdf)

10 Gbps, 20 TB, 1 mL?

10Gbps, 20TB, 1mL?

还有些例外的情况，温度、百分比：
100°C, 100°, 50%

**Comment by vinta** [comment]
不過技術上要區分出單位實在有點難度
考慮到如果是數字與「英文單位」
其實有沒有空格都可以啊，只要一致就行
所以 pangu.js 只會處理數字與「中文單位」之間的空格

**Comment by jeopsh** [comment]
@vinta 确实也是呢！疏忽了技术上的问题了！
单位的种类也不少，而且数字字母还有很多特定组合，就像“3G”。就保持现在这样就好。
还是得谢谢你开发这样实用又有趣的东西。感谢空格之神！:joy:
