### ISSUE TITLE
中文与 <code>English<code> 之间应该加上空格

### ISSUE THREAD

**Issue by yihui** [vinta/pangu.js#97]
例如这篇文章第三段第一句话 https://yihui.name/cn/2012/09/equal-and-arrow/

```html
<p>最初 S 代码中，下划线本身就是赋值符号，例如<code>x_1</code>表示把 1 赋值给 x。</p>
```

其中 `x_1` 前后应该加空格。

**Comment by yimingli** [comment]
另一个相关的例子见这里，第四段第一句 https://zhuanlan.zhihu.com/p/27906502

```
四位学者在2010年<i>Explorations in Economic History</i>的文章中综合多个指标
```

斜体的英文两头应该有空格。
