### ISSUE TITLE
转制 Microsoft Edge 插件

### ISSUE THREAD

**Issue by yzhang-gh** [vinta/pangu.js#99]
可以使用微软提供的[转制工具](https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/porting-chrome-extensions)，只需要改动一个小配置。我测试后发现可以正常使用。

不过发布到 Edge 的插件商店应该还需要申请审核，如果你没有时间我可以代劳

**Comment by vinta** [comment]
@neilsustc 好啊，因為我平常沒有在用 Edge，由你來維護那個插件可能更合適

**Comment by febaoshan** [comment]
edge可以直接从Google的插件市场安装chrome插件

**Comment by yzhang-gh** [comment]
是的哈哈，更方便了
